sys-apps/pyconfig_gen/pyconfig_gen-1.1.9-r1.ebuild

Replacing outdated dependencies with new ones.

Fixed dependencies for sys-apps/pyconfig_gen

---

sys-apps/pyconfig_gen/pyconfig_gen-1.1.9-r1.ebuild

Patching up a ebuild.
Partly #21.

Patched pyconfig to use Sakaki's url.

---

profiles/profiles.desc

This is continium per @perkinslr's comment in #39.

Update profile description for systemd support

---

profiles/targets/genpi64/package.use/dbus

there is no user-session USE flag on that package.
*

Remove package.use/dbus

---

profiles/targets/genpi64/package.use/gcc

Add some flags to the gcc package for better optimizations

---

profiles/targets/genpi64/package.use/mpich

While these are probably good to have for people who use mpich... it's got nothing to do with us.
*

Remove package.use/mpich

---

profiles/targets/genpi64/package.use/gcc

Disable LTO for gcc until the heavy impact on build times is figured out

---

sys-kernel/raspberrypi-initramfs/raspberrypi-initramfs-2.0.0-r2.ebuild

Fix libffi soname in initramfs

---

dev-python/rpi-gpio/rpi-gpio-0.7.0-r1.ebuild

dev-python/rpi-gpio: Update to support Python 3.10.

---

sys-kernel/raspberrypi-kernel/raspberrypi-kernel-5.15.61.ebuild

Boot tested locally, no observed problems
*

Stablize kernel 5.15.61

---

Jenkinsfile

Add jenkinsfile to trigger image build on overlay change

---

profiles/targets/genpi64/packages
profiles/targets/genpi64Exp/packages

Fixes #150
See https://bugs.gentoo.org/835013.

Remove repoman

---

profiles/default/linux/arm64/17.0/genpi64/systemd/parent

Needed by upcoming change in upstream gentoo
*

Change systemd-lite build to use merged-usr

---

profiles/default/linux/arm64/17.0/genpi64/desktop/systemd/parent

Needed by upcoming change in upstream gentoo
*

update systemd-desktop to use merged-usr

---

eclass/pikernel-build.eclass

No functionality changes, just whitespace and line continuations

Minor cleanup of kernel class formatting

---

acct-group/gpio/gpio-0.ebuild
acct-group/gpio/metadata.xml
acct-group/i2c/i2c-0.ebuild
acct-group/i2c/metadata.xml
acct-group/spi/metadata.xml
acct-group/spi/spi-0.ebuild

Remove acct-group entries that are present in upstream gentoo

---

profiles/targets/genpi64desktop/make.defaults

Make desktop profile add to USE, instead of replace

---

profiles/targets/genpi64/make.defaults

Don't overspecify use flags in profile, inherit from parent profiles.

---

profiles/targets/genpi64desktop/package.use/orage

See https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=22d0a2c2cde3083896142745e87e9fc8f4bc425f
*

Remove orage use flags. Package last-righted by gentoo

---

eclass/pikernel-build.eclass
sys-kernel/raspberrypi-kernel/raspberrypi-kernel-5.15.61-r1.ebuild

Not testing yet. Waiting for my local build to finish (will be several days)

Hackjob to attempt fixing the kernel

---

sys-kernel/raspberrypi-kernel/raspberrypi-kernel-5.15.61-r1.ebuild

Compiles locally, waiting to confirm that it installs, but it should.

Some small fixes

---

profiles/targets/genpi64/package.unmask/dist-kernel

Fix missing -r1

---

profiles/targets/genpi64/package.use/genup
profiles/targets/genpi64/packages
profiles/targets/genpi64Exp/package.use/genup
profiles/targets/genpi64Exp/packages

Also remove genup from default set

---

sys-kernel/raspberrypi-kernel/raspberrypi-kernel-6.1.21.ebuild
virtual/dist-kernel/dist-kernel-6.1.21.ebuild

Stabilize kernel 6.1.21 based on user testing

---

sys-kernel/raspberrypi-kernel/raspberrypi-kernel-6.1.58.ebuild
virtual/dist-kernel/dist-kernel-6.1.58.ebuild

Marked unstable, as it is untested.

Add linux kernel 6.1.58 from raspberry pi repo

---

sys-kernel/raspberrypi-kernel/raspberrypi-kernel-6.1.63.ebuild

Add kernel 6.1.63

---

sys-kernel/raspberrypi-kernel/raspberrypi-kernel-6.6.31.ebuild
virtual/dist-kernel/dist-kernel-6.6.31.ebuild

Add kernel 6.6.31 to match latest raspberry pi foundation kernel
