net-wireless/rpi3-wifi-regdom/files/init.d_rpi3-wifi-regdom-1
If the region isn't set early, the wifi may fail to connect because the current rules don't let it see the network.
(For example, American 5GHz wifi)
=> Set the wifi region before starting network

profiles/targets/genpi64/package.use/apache, profiles/targets/genpi64/package.use/nginx
These use-flags are really oddly specific, and don't belong in a profile. Users who want jitsi support can easily enable it themselves, and if we want to provide binpkgs for this, it can be done at a different stage of the build process.
=> Remove oddly specific profile wide useflags

sys-apps/pyconfig_gen/pyconfig_gen-1.2.0.ebuild
There are a few minor issues with the last release version of pyconfig_gen from sakaki's repo.  The setuptools version doesn't match the package version and the "shebang" for starting the script reads from env instead of using `/usr/bin/python3`.  (As this is a system tool, it needs to respect `eselect python`).  
When setting up this GH org, skipping pyconfig_gen was an oversight, which has now been correctd, and the new version is released there.  This ebuild uses the new URL to go with the new release version.
* Relates to #21
=> Update pyconfig_gen version

profiles/default/linux/arm64/17.0/genpi64/desktop/systemd/parent, profiles/default/linux/arm64/17.0/genpi64/systemd/parent
I broke relative paths for the systemd profile when I re-arranged things. Oops.
This uses the reponame:path syntax instead of a full relative path.
Should work right? If not, what is the genpi64 profile missing to let this work?
=> Use repo scoping syntax instead of relative path

media-libs/libsdl2/libsdl2-2.0.14-r1.ebuild, profiles/targets/genpi64/package.mask/sdl2
Added a fix for building libsdl2. The following bugs have been fixed:
1:
```
--- Invalid atom in /var/db/repos/genpi64/profiles/targets/genpi64/package.mask/sdl2: media-libs/libsdl2::gentoo
```
2:
```
/usr/lib/gcc/aarch64-unknown-linux-gnu/10.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: SDL_rpimouse.c:(.text+0x104): undefined reference to `vc_dispmanx_element_change_attributes'
/usr/lib/gcc/aarch64-unknown-linux-gnu/10.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: SDL_rpimouse.c:(.text+0x118): undefined reference to `vc_dispmanx_update_submit'
/usr/lib/gcc/aarch64-unknown-linux-gnu/10.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: build/.libs/SDL_rpimouse.o: in function `RPI_FreeCursor':
SDL_rpimouse.c:(.text+0x1d4): undefined reference to `vc_dispmanx_update_start' …
```
=> Fix build libsdl2

profiles/targets/genpi64/packages, sys-apps/rpi3-init-scripts/rpi3-init-scripts-1.1.5-r3.ebuild
Removed the wierd dependency of NetworkManager in rpi3-init-scripts and added new package requirement on net-misc/dhcpcd.
The new DHCP client will be installed, but will not be enabled by default by this change.
=> Patching rpi3-init-scripts and new packages to profile list

profiles/default/linux/arm64/17.0/genpi64/desktop/systemd/parent
At some point the location of the desktop profile was changed. This fixes the parent relationship.
Problem detected by repoman.
=> Fix systemd desktop profile

sys-apps/rpi-onetime-startup/files/autoexpand_root.service-5, sys-apps/rpi-onetime-startup/files/autoexpand_root.sh-5, sys-apps/rpi-onetime-startup/rpi-onetime-startup-1.0-r5.ebuild, sys-apps/rpi3-init-scripts/files/init.d_autoexpand_root-5, sys-apps/rpi3-init-scripts/rpi3-init-scripts-1.1.5-r5.ebuild
Remove password setting and service enabling code, which shouldn't be happening on firstboot in the first place. These tasks should be done in the image builder only.
=> Fix auto expand apps using a helper script. 

sys-kernel/raspberrypi-kernel/raspberrypi-kernel-5.10.11.ebuild
=> Override function from kernel-install eclass to skip checking of kernel.release file(s).

profiles/targets/systemd/packages
It feels quite wierd to not have dig, mtr or iperf by default.
=> Update systemd profile packages

profiles/targets/genpi64desktop/packages
Remove x11-misc/rpi3-safecursor from this list, it was delete with commit #93
x11-misc/rpi3-safecursor was delete from the overlay, it should be removed from the packages list.
*
=> Remove x11-misc/rpi3-safecursor

profiles/targets/genpi64/make.defaults
We have no reason to specify the emulation targets for qemu in the genpi64 profile. Our project only ever uses the host qemu to do anything.
*
=> Don't specify QEMU settings

profiles/targets/genpi64desktop/make.defaults
As with https://github.com/GenPi64/genpi64-overlay/pull/119 , sanitize should be left to default.
The mudflap flag is no longer available in newer gcc (superseded by sanitize, i believe. I think gcc removed mudflap as a library back in 2012?)
*
=> Don't set USE="-mudflap -sanitize" on desktop profile

profiles/targets/genpi64/make.defaults
Because USE=-sanitize is set in the genpi64 profile, we end up building GCC again during the build process. The default settings from upstream have USE=sanitize, not USE=-sanitize.
GCC is one of the most time consuming packages to build, so we're better off just keeping the upstream settings to avoid rebuilds.
*
=> Don't set USE=-sanitize in the profile. Causes GCC to be rebuilt

profiles/targets/genpi64/package.use/php
Nothing in our project touches php.
End users can specify these flags if they want.
*
=> Don't specify default use flags for php

profiles/targets/genpi64/package.mask/sdl2
The masked versions of sdl2 are no longer in the gentoo tree.
*
=> delete package.mask/sdl2 , obsolete

profiles/targets/genpi64/package.use/llvm
Latest stable aarch64 llvm is 13, which does not have the gold useflag.
*
=> delete package.use/llvm, unneeded

profiles/targets/genpi64/package.use/python_3_9
Prevents updates against newest upstream gentoo portage tree.
*
=> Delete forced setting of python_3_9 in profile

profiles/targets/genpi64/package.use/polkit
duktape is now the default setting with upstream gentoo. We no longer need to specify this ourselves.
*
=> Remove package.use/polkit

profiles/targets/genpi64/package.use/brcm43430-firmware
No available versions of the linux-firmware package have the use flag listed.
I haven't yet evaluated if the brcm43430-firmware package could be improved
*
=> Remove linux-firmware from package.usr/brcm43430-firmware

profiles/targets/genpi64/package.accept_keywords/micropython
It shouldn't be for just a specific version.
=> Update accept_keywords for micropython

profiles/targets/genpi64/package.use/elogind
Now that gentoo upstream's polkit has ductape instead of spidermonkey (and therefore, doesn't use rust), why disable polkit for elogind?
Note that I don't use openrc, so I legitimately don't know what would motivate someone not to use polkit with elogind, if not the rust dependency.
*
=> discussion: Allow elogind to use polkit

profiles/targets/genpi64/package.mask/rust
Let's not mask rust anymore
It may not build easilly, but we shouldn't mask it I don't think.
=> profiles/targets/genpi64/package.mask: Do not mask rust

profiles/targets/genpi64/package.mask/notification-daemon
This setting doesn't apply to the non-desktop profile. Lets remove it. Arguably, it's the users choice regardless.
*
=> Remove non-desktop setting for notification-daemon

acct-group/gpio/gpio-0-r1.ebuild, acct-group/gpio/metadata.xml, acct-group/spi/metadata.xml, acct-group/spi/spi-0-r1.ebuild, profiles/targets/genpi64/package.unmask/acct-group
This fixes gentoo having masked the packages for removal...
=> Pull over the acct-group/spi and acct-group/gpio from gentoo

profiles/targets/genpi64/packages
eutils.eclass no longer exists. My 2c is that it shouldn't be in the profile because it is a non-standard tool that's not necessary for operating Gentoo on the raspberry pi.
=> Remove app-portage/showem from genpi64 profile.
